### ISSUE TITLE
Don't know if it's a bug

### ISSUE THREAD

**Issue by dracony** [ramonvictor/rv-jquery-fontsize#1]
The central button doesn't become disabled after you click on it , and there is little to no reason for it to stay enabled (since you do disable the left and right buttons when the limit is reached). Idk if you planned it to be like this =)

**Comment by ramonvictor** [comment]
Thanks for the feedback, @dracony.
It makes sense. I will definitely take a look at this.

**Comment by ramonvictor** [comment]
Suggestion implemented, @dracony!

You can check it on [live demo page](http://www.ramonvictor.com/demo/fontsize/fontsize2.0/).

Thanks again.
