### ISSUE TITLE
Separate Store.js Dependency

### ISSUE THREAD

**Issue by webavant** [ramonvictor/rv-jquery-fontsize#3]
It is common to compile all of a site's javascript into one file. The XHR request of the Store.js file is an unnecessary additional request.  Maybe consider using a Bower package instead, or just providing instructions to integrate without depending on loading it via XHR.  Great plugin.

**Comment by ramonvictor** [comment]
Hi @webavant,
First of all, sorry for delaying the reply. It's really nice to see your feedback.
I've updated a new version of the plugin and right now the Store.js file is been loaded in the 'conventional' way.
Currently, I suppose it's easier to integrate with any of the tools you mentioned. I'm not an expert in Grunt, so I tried to let it open to developers handle the dependencies the way they want. 
Hope these updates help developers to make their apps improve.
Thanks again!

**Comment by webavant** [comment]
No problem!  Great work.  Best font-resize plugin by far.
