### ISSUE TITLE
How use html structure

### ISSUE THREAD

**Issue by brunowego** [ramonvictor/rv-jquery-fontsize#4]
I need ignore the template and use a custom HTML, is possible to do it?

**Comment by brunowego** [comment]
I get a error: h.$resetButton is undefined

**Comment by brunowego** [comment]
Works for me:

``` javascript
jQuery(document).ready(function($) {
  $.rvFontsize({
    targetSection: 'header .header, #nav, #content, footer .footer-top, footer .menus',
    store: true,
    controllers: {
    }
  });
});
```

**Comment by brunowego** [comment]
I made a module for CMS Joomla! 3.x, see: https://github.com/joomlapro/mod_fontsize

Thanks to build this plugin!

**Comment by ramonvictor** [comment]
Really happy to know you are using my plugin. Thanks! :)

Please, add just this new line inside the 'controllers' object:

``` javascript
jQuery(document).ready(function($) {
  $.rvFontsize({
    targetSection: 'header .header, #nav, #content, footer .footer-top, footer .menus',
    store: true,
    controllers: {
        append: false
    }
  });
});
```

On the html, you would have something like this:

``` html
<div class="btn-group">
    <a href="#" class="rvfs-decrease btn">A-</a>
    <a href="#" class="rvfs-reset btn">A</a>
    <a href="#" class="rvfs-increase btn">A+</a>
</div>
```

You can change the tags, but don't forget to keep the `rvfs-*` classes because they
are responsible to attach the javascript events.

Really appreciate your plugin!

**Comment by brunowego** [comment]
Thanks a lot to help me and reply this issue :dart:

**Comment by eytanchen** [comment]
This happened to me as well. It looks like there is an error in the script.
The call to: _self.bindControlerHandlers();  only runs: if( _self.options.controllers.append !== false )
I took it outside this statement and it works fine.
